Feature/best practices
stacc/react-guild pull request #7
Opened 2023-05-12 10:55 UTC by robinsandborg

2023-05-16 07:07 UTC, Gawdfrey commented on best-practices/authentication.md
Maybe link to [AuthJs](https://authjs.dev/) instead?
You still have to use next-auth for nextjs though

2023-05-16 07:09 UTC, Gawdfrey commented on best-practices/components/forms.md
> +  In order to keep the details of the field in one place, it can be useful to add `MyField.validationSchema` and `MyField.defaultValue` to the field component.
Would probably include a code snippet to show how this is done in practice.

2023-05-16 07:10 UTC, Gawdfrey commented on best-practices/components/forms.md
> +  A pattern often used in our projects is to create a `useFormConnect` that wraps the `useController` hook from react-hook-form and gets the field and fieldState.error.message props from the controll
Either a code snippet or a link to showcase how its done. Easily copy pasteable!

2023-05-16 07:11 UTC, Gawdfrey commented on best-practices/components/libraries.md
> +- Can be difficult to translate styles from the Radix Docs to tailwind.
All(?) radix components have tailwind examples now.

2023-05-16 07:13 UTC, Gawdfrey commented on best-practices/components/libraries.md
> +- Cannot be used directly in server components (NextJs app dir)
Would probably nuance this with `These components require javascript, and if you want to utilize these components you need to append them with the "use client" syntax`. This applies to everywhere this sentence is used.

2023-05-16 07:14 UTC, Gawdfrey commented on best-practices/data-fetching.md
Should we mention TRPC? We have few use cases on the customer teams, but it is one of the most widely used data fetching libraries.

2023-05-16 07:16 UTC, Gawdfrey commented on best-practices/project-structure.md
> +- Use named exports instead of default exports. This makes it easier to find where a component is imported.
Should probably have a small code snippet for this. I have a sense that some might not understand what this means from the getgo

2023-05-16 07:16 UTC, Gawdfrey commented on best-practices/project-structure.md
> +- Have separate folders for components, hooks, utils, api, pages, etc.
We could probably link to one of our templates?
Speaking of templates, we should probably set up a one click next starter in nextjs? @XSlemX @robinsandborg

2023-05-16 07:17 UTC, Gawdfrey commented on best-practices/seo.md
Link to Nextjs seo documentation. Should probably have a section on why client side seo does not matter 😂

2023-05-16 07:21 UTC, Gawdfrey commented on best-practices/testing.md
Would probably include testwright and vitest as recomendations here.

2023-05-16 07:22 UTC, Gawdfrey requested changes
I've left a couple of comments for recommended changes.
Lets discuss and how we will move forward.

2023-05-16 07:27 UTC, Gawdfrey commented on best-practices/starting-a-new-project.md
> +As of 2023-05-01, we recommend sticking to the tried and true pages structure for Next.js, but we expect this to change soon as the App directory structure becomes more stable and mature.
Use a different date format as well

2023-06-07 12:58 UTC, robinsandborg commented on best-practices/components/libraries.md
> +- Can be difficult to translate styles from the Radix Docs to tailwind.
Oh, nice! Did not catch that, neatly hidden away

2023-06-07 13:08 UTC, robinsandborg commented on best-practices/starting-a-new-project.md
> +As of 2023-05-01, we recommend sticking to the tried and true pages structure for Next.js, but we expect this to change soon as the App directory structure becomes more stable and mature.
Is it outdated?

2023-06-08 04:52 UTC, Gawdfrey commented on best-practices/project-structure.md
> +- Have separate folders for components, hooks, utils, api, pages, etc.
I was thinking about backstage templates. [This](https://backstage.stacc.dev/create?filters%5Bkind%5D=template&filters%5Buser%5D=all) one for example spins up a fully working flow instance. Backstage can be a nice place to gather them all. But as you mention having one for frontend might not make sense as it is updated so frequently.

2023-06-08 04:54 UTC, Gawdfrey commented on best-practices/data-fetching.md
Lets not do that at this time. As mentioned we have rarely used it on our projects so far.

2023-06-08 04:55 UTC, Gawdfrey approved these changes
LGTM! Good first iteration, lets get it out and get some feedback!

2023-06-08 08:18 UTC, merged